Reuse existing oauth tokens in graphql server
Soluto/agogos pull request #76
Opened 2019-08-04 14:56 UTC by AvivRubys

2019-08-04 16:26 UTC, tomeresk approved these changes
Are there no cases where the cached token expires or needs to be invalidated?

2019-08-04 19:09 UTC, AleF83 requested changes
Great idea!
I just think maybe not to store all token sources in one cache but as a property of clientCredentials object.
So it can be more generic.

2019-08-05 07:20 UTC, AvivRubys commented
@tomeresk the `oauth2` library [takes care of that](https://github.com/golang/oauth2/blob/master/clientcredentials/clientcredentials.go#L80)
@AleF83 good suggestion, see latest commit. This also has the benefit of not needing to hash anything - we can just use the scope as the id, because the cache is bound to the rest of the parameters anyway since it's on the same object.

2019-08-05 11:24 UTC, AleF83 approved these changes

2019-08-05 11:27 UTC, merged